### ISSUE TITLE
"Access is denied. Please contact support." when Authorising

### ISSUE THREAD

**Issue by HughPH** [embbnux/ringcentral-embeddable-electron-app#2]
As above, I get to the list of things that the app wants to do, click "Authorize" and it takes me back to the white page with a "Sign In" button and a red message appears briefly to say "Access is denied. Please contact support."

**Comment by mihaimm** [comment]
Same here. I suspect this has something to do with the Authorized Apps from RingCentral. But don't know how this can be authorized...

**Comment by embbnux** [comment]
@HughPH @mihaimm Can you try again to authorize. We fix some authorization issue in no-US user.

**Comment by embbnux** [comment]
Closed for inactive. Feel free to reopen if issue still exists.
